apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-store-pv
spec:
  capacity:
    storage: 5000Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: image-store-class
  # A hostPath volume mounts a file or directory from the host node's file system into your pod
  hostPath:
    path: "/mnt/data/images"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-store-pvc
spec:
  # map to storageClassName in pv
  storageClassName: image-store-class
  resources:
    requests:
      storage: 5000Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-image
spec:
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: ngoctd/ecommerce-image:latest
        volumeMounts:
        - name: data
          mountPath: /app/images
        resources:
          limits:
            memory: "50Mi"
            cpu: "200m"
        # ports:
        # - containerPort: 8080
        # - containerPort: 3000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: image-store-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image-service
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: image-host
spec:
  type: NodePort
  selector:
    app: image-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30016
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: image-srv
#   labels:
#     name: image-srv
# spec:
#   rules:
#   - host: ecommerce.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: 
#             port: 
#               number: <Port>
